env:
  browser: true
  es6: true
  commonjs: true
  jquery: true
globals:
  localStore: readonly
  html2canvas: readonly
  setHighlightTheme: readonly
  darkFunctions: readonly
extends:
  - 'eslint:recommended'
rules:
  indent:
    - off
  linebreak-style:
    - error
    - unix
  quotes:
    - 2
    - double
    - avoidEscape: true
  semi:
    - error
    - always
  no-unused-vars:
    - off

